# Generated by Django 4.0.2 on 2022-03-08 22:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('gender', models.CharField(max_length=1)),
            ],
        ),
        migrations.AlterField(
            model_name='hotel',
            name='phone_number',
            field=models.CharField(max_length=21, validators=[django.core.validators.RegexValidator(message='Ensure this field has 10-20 digits.', regex='^[0-9]{10,20}$')]),
        ),
    ]
