# Generated by Django 4.0.2 on 2022-03-09 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0002_guest_alter_hotel_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('confirmation_number', models.CharField(max_length=10)),
                ('guests', models.JSONField()),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotels.hotel')),
            ],
        ),
        migrations.DeleteModel(
            name='Guest',
        ),
    ]
