# Generated by Django 4.0.2 on 2022-03-09 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0003_reservation_delete_guest'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='check_in',
            field=models.DateField(default='2022-03-09'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='check_out',
            field=models.DateField(default='2022-03-10'),
            preserve_default=False,
        ),
    ]
