# Generated by Django 4.0.2 on 2022-03-10 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0004_reservation_check_in_reservation_check_out'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='guests',
        ),
    ]
